# name this file 'solutions.py'
"""Volume II Lab 13: Optimization Packages I (scipy.optimize)
Sean Wade
MATH 323
8/1/2015
"""

import numpy as np
from matplotlib import pyplot as plt
from scipy import optimize as opt

def prob1():
    """Use the minimize() function in the scipy.optimize package to find the
    minimum of the Rosenbrock function (scipy.optimize.rosen) using the
    following methods:
        Nelder-Mead
        Powell
        CG
        BFGS
        Newton-CG (test with and without the hessian)
        Anneal
        L-BFGS-B
        TNC
        COBYLA
        SLSQP
    Use x0 = np.array([4., -2.5]) for the initial guess for each test.
    
    Print a statement answering the following questions:
        Which algorithm(s) take(s) the least number of iterations?
        Which algorithm(s) fail to find the (correct) minimum?
    """
    # opt.minimize(opt.rosen, x0, method='nelder-mead', options={'xtol': 1e-8})
    print "Question 1 answers:"
    print "The best is Powell"
    print "COBYLA fails"

def prob2():
    """Explore the documentation on the function scipy.optimize.basinhopping()
    online or via IPython. Use it to find the global minimum of the multmin()
    function given in the lab, with initial point x0 = np.array([-2, -2]) and
    the Nelder-Mead algorithm. Try it first with stepsize=0.5, then with
    stepsize=0.2.

    Return the minimum value of the function with stepsize=0.2.
    Print a statement answering the following question:
        Why doesn't scipy.optimize.basinhopping() find the minimum the second
        time (with stepsize=0.2)?
    """
    def multimin(x):
        r = np.sqrt((x[0]+1)**2 + x[1]**2)
        return r**2 * (1+np.sin(4*r)**2)

    x0 = np.array([-2, -2])
    res = opt.basinhopping(multimin, x0, stepsize=0.2, minimizer_kwargs={'method':'nelder-mead'})
    print "Question 2 Answers"
    print "It dosnt find the lowest with .2 because it is too small a step to get over the hill and falls in, .5 is big enough to make it over"
    print "Step .2: (-2.597, -1.694)"
    print "The answer is 5.48816865696"
    return multimin(res.x)


def prob3():
    """Find the roots of the system
    [       -x + y + z     ]   [0]
    [  1 + x^3 - y^2 + z^3 ] = [0]
    [ -2 - x^2 + y^2 + z^2 ]   [0]

    Returns the values of x,y,z as an array.
    """
    def func(x):
        return [-x[0] + x[1] + x[2], 1+x[0]**3 - x[1]**2 + x[2]**3, -2-x[0]**2+x[1]**2+x[2]**2]

    def jac(x):
        return np.array([[-1,1,1], [3*x[0]**2, -2*x[1], 3*x[2]**2], [-2*x[0], 2*x[1], 2*x[2]]])

    sol = opt.root(func, [0,0,0], jac=jac, method='hybr')
    return sol.x


def prob4():
    """Use the scipy.optimize.curve_fit() function to fit a heating curve to
    the data found in `heating.txt`. The first column of this file is time, and
    the second column is temperature in Kelvin.

    The fitting parameters should be gamma, C, and K, as given in Newton's law
    of cooling.

    Plot the data from `heating.txt` and the curve generated by curve_fit.
    Return the values gamma, C, K as an array.
    """
    def func(t,g,c,k):
        return 290 + 59.43/g + k*np.exp((-g * t)/c) 

    data = np.loadtxt('heating.txt')
    x = data[:,0]
    y = data[:,1]
    popt, pcov = opt.curve_fit(func,x,y)
    plt.plot(x,y)
    plt.plot(x,func(x,popt[0],popt[1],popt[2]))
    plt.show()
    return popt
